name: pull-request

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  push:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup pre-commit
        uses: ./.github/actions/setup-precommit

      - name: Verify pre-commit installation
        run: pre-commit --version

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        id: run_precommit
        run: |
          pre-commit run -a --show-diff-on-failure || echo "pre-commit checks failed"

      - name: Notify on failure to run pre-commit
        if: steps.run_precommit.outcome == 'failure'
        run: echo "Pre-commit checks encountered issues. Please review the output above."

      - name: Report summary
        run: |
          if [[ "${{ steps.run_precommit.outcome }}" == "failure" ]]; then
            echo "One or more pre-commit checks failed."
          else
            echo "All pre-commit checks passed."
          fi
