name: pull-request
description: Run quality checks and tests on pull requests pushed to the main branch

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  push:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: pre-commit run -a --show-diff-on-failure
